// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    'intro',
    'architecture',
    'improvements',

    {
      type: 'category',
      label: 'Arquivos de Código',
      collapsed: false,
      items: [
        // Entrada da aplicação
        'files/server',
        // Pacote backend/api
        'files/backend-api',
        // Camada API
        'files/routes',
        'files/api-init',
        // Backend core
        'files/app',
        'files/config',
        'files/services',
        'files/state',
        // Processamento de dados
        'files/excel-processor',
        'files/encoding-repair',
        'files/correction-helper',
        'files/report-generator',
        // Integração externa
        'files/powershell-executor',
        // Frontend
        'files/index-html',
      ],
    },

    {
      type: 'category',
      label: 'Módulos & Integrações',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'modules' },
      ],
    },
  ],
};

export default sidebars;
